export * from "./section.controller";
export * from "./subject.controller";
export * from "./timeTable.controller";
export * from "./student.controller";
export * from "./hourlyAttendance.controller";
export * from "./dayAttendance.controller";
export * from "./subjectSectionHours.controller";
export * from "./user.controller";
export * from "./report.controller";
// export * from "./reason.controller";
