export * from "./section.routes";
export * from "./subject.routes";
export * from "./timeTable.routes";
export * from "./student.routes";
export * from "./hourlyAttendance.routes";
export * from "./dayAttendance.routes";
export * from "./subjectSectionHours.routes";
export * from "./user.routes";
export * from "./report.routes";
// export * from "./reason.routes";
